services:
  redis:
    image: redis:7.4-alpine
    container_name: smart-rate-limiter-redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: smart-rate-limiter-app
    depends_on:
      redis:
        condition: service_healthy
    environment:
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: "6379"
    ports:
      - "8081:8081"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: smart-rate-limiter-frontend
    depends_on:
      app:
        condition: service_started
    environment:
      NEXT_PUBLIC_API_BASE_URL: /api/proxy
      BACKEND_INTERNAL_URL: http://app:8081
    ports:
      - "3000:3000"
