services:
  redis:
    image: redis:7.4-alpine
    container_name: smart-rate-limiter-redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: smart-rate-limiter-app
    depends_on:
      redis:
        condition: service_healthy
    environment:
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: "6379"
    ports:
      - "8081:8081"
