services:
  - type: web
    name: smart-rate-limiter-api
    runtime: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    healthCheckPath: /actuator/health
    envVars:
      - key: SPRING_DATA_REDIS_HOST
        fromService:
          type: redis
          name: smart-rate-limiter-redis
          property: host
      - key: SPRING_DATA_REDIS_PORT
        fromService:
          type: redis
          name: smart-rate-limiter-redis
          property: port
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRATION
        value: "3600000"
      - key: SPRING_DATASOURCE_URL
        value: jdbc:h2:mem:ratelimiter
      - key: DB_USERNAME
        value: sa
      - key: DB_PASSWORD
        sync: false

  - type: redis
    name: smart-rate-limiter-redis
    plan: free
    ipAllowList: []